databases:
  - name: myapp
    databaseName: myapp_db_25l2
    user: myapp_user

services:
  - type: web
    name: myapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false